    const categories = {
        "category": [
        {
            "id": "foods",
            "name": "Comida",
            "words": ["Albaricoque", "Almendra", "Arándano", "Avellana", "Bayas", "Cacahuete", "Carambola", "Castaña", "Cereza", "Chirimoya", "Ciruela", 
            "Coco", "Cucurbitáceas", "Dátil", "Frambuesa", "Fresa", "Fruta de la pasión", "Grosella espinosa", "Grosella negra", "Grosella roja", "Higo", "Kaki", "Kiwi", "Limón", 
            "Litchi", "Mandarina", "Mango", "Manzana", "Melocotón", "Melón", "Naranja", "Nectarina", "Nuez", "Níspero", "Pacana", "Papaya", "Pera", "Pistacho", "Piña", "Plátano", 
            "Pomelo", "Sandía", "Uva", "Zarzamora", "Acelga", "Ajo", "Alcachofa", "Apio", "Ascalonia", "Berenjena", "Boniato", "Borraja", "Brócoli", "Calabacín", "Calabaza", "Cebolla", 
            "Champiñón", "Chirivía", "Col de Bruselas", "Coliflor", "Colinabo", "Colirrábano", "Endibia", "Escarola", "Espinaca", "Espárrago", "Guisante", "Haba", "Hierba de los canónigos", 
            "Judía verde", "Lechuga", "Maíz", "Nabo", "Patata", "Pepino", "Perejil", "Pimiento", "Puerro", "Remolacha", "Rábano", "Solanáceas", "Tomate", "Zanahoria", "Agua",
            "Albondigas","Alitas de Pollo","Aros de Cebolla","Arroz","As","Azúcar","Baguette","Banderilla","Batido","Bebida","Brownie","Café","Caldillo de Mariscos","Calzon Roto",
            "Camote","Canela","Caramelo","Carne a la Borgoña","Carne Mechada","Carne Mongoliana","Cazuela","Cereal","Cerveza","Ceviche","Champán","Chancaca","Chaparrita","Charquicán",
            "Cheesecake","Chocolate","Choripan","Chorizo","Chorrillana","Chucrut","Chupe de Jaiba","Completo","Coñac","Conejo","Costillar","Crepe","Croissant","Croqueta","Cupcake",
            "Doblada","Donas","Dulce","Empanada","Enchilada","Encurtidos","Endulzante","Ensalada","Ensalada César","Ensalada Chilena","Estofado","Fajita","Fetuccini","Fideos",
            "Fritura","Galleta","Ganso","Gaseosa","Gnocchi","Guacamole","Guatita","Hamburguesa","Helado","Hot Dog","Huevo Centenario","Humita","Italiano","Jalea","Jamon","Jengibre",
            "Jugo","Kebab","Ketchup","Kuchen","Lasaña","Leche","Licor","Locos a la Parmesana","Macarrones","Macarrones con Queso","Manjar","Mantequilla","Manzana Acaramelada",
            "Margarina","Marraqueta","Maruchan","Mayonesa","Merluza","Mermelada","Milanesa","Milkshake","Mostaza","Mote con Huesillo","Muffin","Nugget","Nutella",
            "Ostiones a la Parmesana","Paella","Palitos de Ajo","Palitos de Queso","Pan","Panqueque","Pantruca","Papas Fritas","Papas Gratinadas","Pasta","Pastel","Pastel de Choclo",
            "Pastel de Jaiba","Paté","Pato","Pescado","Pez Globo","Pie","Pisco","Pizza","Pollo","Pollo Arvejado","Pollo Asado","Pollo Mongoliano","Porotos con Mazamorra",
            "Porotos con Rienda","Porotos Granados","Puré","Queque","Quesadilla","Queso","Ramen","Ratatouille","Ravioles","Risotto","Ron","Sal","Salame","Salsa BBQ","Salsa de Ajo",
            "Salsa de Queso","Salsa de Soya","Sashimi","Sidra","Soda","Sopa","Sopa de Tomate","Sopaipilla","Sorrentinos","Spaghetti","Sucralosa","Sundae","Sushi","Taco","Tamal","Té",
            "Tofu","Tomaticán","Torta","Trufa","Vienesa","Vino","Vino Blanco","Vino Tinto","Vodka","Waffle","Wasabi","Wrap","Yogurt", "Palta (sí, palta)"]
        },
        {
            "id": "sports",
            "name": "Deportes",
            "words": ["Acrobacia Aérea", "Acuatlón", "Aeromodelismo", "Aerostato", "Aikido", "Airboard", "Airsoft", "Ajedrez", "Ala Delta", "Alpinismo",
            "Acrobacia Aérea", "Acuatlón", "Aeromodelismo", "Aerostato", "Aikido", "Airboard", "Airsoft", "Ajedrez", "Ala Delta", "Alpinismo", "Alquerque", "Piques",
            "Arrastre de piedra", "Artes marciales mixtas", "Ataxx", "Atletismo de fuerza", "Autocross", "Automovilismo de velocidad", "Autoslalom", "Backgammon", "Baloncesto",
            "Balonmano", "Balonmano de playa", "Bando", "Bandy", "Barranquismo", "Biatlón", "Bikepolo", "Billar", "BMX", "Boardercross", "Bobsleig", "Bochas", "Bodyboarding",
            "Bojutsu", "Bokator", "Bossaball", "Bowling", "Bowls", "Boxeo", "Bridge", "Broomball", "Buceo", "Bádminton", "Béisbol", "Calva", "Camogie", "Campo a través",
            "Capoeira", "Carrera de Drag Boat", "Carreras de Camellos", "Carreras de destrucción", "Carreras de larga distancia", "Carreras de medio fondo", "Carreras de palomas",
            "Carreras de vallas", "Carreras de Velocidad", "Carrom", "Chess Boxing", "Choy Li Fat", "Ciclismo artístico", "Ciclismo de montaña", "Ciclismo en pista", 
            "Ciclismo en ruta", "Ciclobol", "Ciclocross", "Clavados", "Corta de troncos", "Croquet", "Cross-Country", "Críquet", "Culturismo", "Curling", "Damas", "Dardos",
            "Decatlón", "Deportes caninos", "Deportes ecuestres", "Descenso de ríos", "Dirtsurfing", "Drifting", "Duatlón", "Enduro", "Endurocross", "Epaminondas", "Escalada",
            "Escalada en hielo", "Esgrima", "Eslálom paralelo", "Espeleología", "Esquí acuático", "Esquí de travesía", "Excursionismo", "Floorball", "Freeride", "Freestyle slalom",
            "Freeze", "Fuerza de agarre", "Full contact", "Futbolín", "Futvóley", "Fútbol", "Fútbol americano", "Fútbol australiano", "Fútbol de mesa", "Fútbol gaélico", "Fútbol playa",
            "Fútbol sala", "Fútbol subacuático", "Fútbol tenis", "Fútgolf", "Gateball", "Gatka", "Gimnasia acrobática", "Gimnasia aeróbica", "Gimnasia artística", "Gimnasia en trampolín",
            "Gimnasia rítmica", "Glima", "Golf", "Gouren", "Hakko Ryu", "Halterofilia", "Hapkido", "Heptatlón", "Herradura", "Hidrospeed", "Hill climbing", "Hockey", "Hockey de aire",
            "Hockey de mesa", "Hockey en monociclo", "Hockey playa", "Hurling", "Hydrospeed", "Iaido", "Ice Stock Sport", "Indiaca", "Jeet Kune Do", "Jiu jitsu", "Judo",
            "Juego de la Soga", "Karate", "Karting", "Kayak Polo", "Kendo", "Kenjutsu", "Kenpo", "Kick Boxing", "Kickball", "Kite Landboarding", "Kiteboarding", "Kitesurf",
            "Kneeboarding", "Komikan", "Korfball", "Kronum", "Kung Fu", "Kuntao", "Lacrosse", "Lanzamiento de cuchillos", "Lanzamientos", "Lasca", "Laser Tag", "Lethwei",
            "Levantamiento de piedras", "Levantamiento de potencia", "Longboard", "Lucha canaria", "Lucha grecorromana", "Lucha leonesa", "Lucha libre olímpica",
            "Lucha Libre profesional", "Luge", "Mahjong", "Mancala", "Marcha atlética", "Monociclismo de montaña", "Montañismo", "Motociclismo de velocidad", "Motociclismo estilo libre",
            "Motocross", "Motonieve", "Motonáutica", "Motonáutica de resistencia", "Motonáutica de velocidad", "Mountainboarding", "Muay Thai", "Nanbudo", "Natación",
            "Natación sincronizada", "Netball", "Neutón", "Ninjutsu", "Pa Kua Chang", "Padbol", "Paintball", "Paleta frontón", "Paracaidismo", "Parapente", "Parkour",
            "Patinaje agresivo", "Patinaje artístico", "Patinaje artístico sobre Hielo", "Patinaje artístico sobre ruedas", "Patinaje de gravedad", "Patinaje extremo sobre hielo",
            "Patinaje sincronizado", "Pelota valenciana", "Pelota vasca", "Pencak silat", "Pentatlón moderno", "Petanca", "Ping Pong", "Piragüismo", "Polo", "Polo sobre elefantes",
            "Polocrosse", "Proresu", "Pruebas combinadas", "Puenting", "Pulsear", "Pádel", "Póker", "Rafting", "Rally", "Rally motonáutico", "Rallycross", "Remo", "Reversi",
            "Rithmomachia", "Roller Dance", "Roller Derby", "Rugby", "Rugby de playa", "Rugby subacuático", "Ráquetbol", "Salto atlético", "Salto base", "Salto de esquí", "Sambo",
            "San Da", "Sandboarding", "Savate", "Schewingen", "Scrabble", "Senderismo", "Shinty", "Shogi", "Shoot Fighting", "Shoot Wrestling", "Shorinji Kempo", "Showball",
            "Sidecarcross", "Skateboarding", "Skeleton", "Ski Archery", "Ski Flying", "Skiboarding", "Skibobbing", "Skijóring", "Skimboarding", "Skurfing", "Skysurfing",
            "Slamball", "Sled Dog Racing", "Snakeboard", "Snowboard de montaña", "Snowboarding", "Snowcross", "Snowkiting", "Snowskate", "Soft Tenis", "Speedcubing", "Speedway",
            "Squash", "Ssirum", "Stratego", "Street Luge", "Subbuteo", "Supercros", "Supermoto", "Superquad", "Surakarta", "Surf", "Sóftbol", "Taekwondo", "Taichí", "Taijutsu",
            "Tangsudo", "Tchoukball", "Telemark", "Tenis", "Tenis de Mesa", "Tenis de Playa", "Tennikoit", "Tiro con arco", "Tiro deportivo", "Trail Running", "Trial",
            "Trial en monociclo", "Triatlón", "Ultimate", "Vela", "Voleibol", "Voleibol de playa", "Voleibol patada", "Wakeboarding", "Wallyball", "Waterbasket", "Waterpolo",
            "Watervoley", "Wiffle Ball", "Windsurf", "Wing Chun", "Wingsuit", "Yagli Gures"]
        }, 
        {
            "id": "countries",
            "name": "Países",
            "words": ["Andorra", "Emiratos Árabes Unidos", "Antigua y Barbuda", "Albania", "Armenia", "Argentina", "Austria", "Australia", "Aruba", "Islas Aland", "Azerbaiyán",
            "Bosnia y Herzegovina", "Barbados", "Bangladés", "Bélgica", "Bulgaria", "Baréin", "Bermudas", "Brunéi", "Bolivia", "Brasil", "Bahamas", "Bielorrusia", "Belice", 
            "Canadá", "República Centroafricana", "Suiza", "Costa de Marfil", "Chile", "China", "Colombia", "Costa Rica", "Chipre", "República Checa", "Alemania", "Dinamarca", 
            "República Dominicana", "Argelia", "Ecuador", "Estonia", "Egipto", "Eritrea", "España", "Unión Europea", "Finlandia", "Islas Feroe", "Francia", "Georgia", "Guayana Francesa",
            "Guernsey", "Gibraltar", "Groenlandia", "Guadalupe", "Grecia", "Guatemala", "Guam", "Guyana", "Hong Kong", "Honduras", "Croacia", "Hungría", "Indonesia", "Irlanda", 
            "Israel", "Isla de Man", "India", "Irak", "Irán", "Islandia", "Italia", "Jersey", "Jamaica", "Jordania", "Japón", "Kenia", "Kirguistán", "Camboya", "Corea del Sur", 
            "Kuwait", "Kazajistán", "Laos", "Líbano", "Santa Lucía", "Liechtenstein", "Sri Lanka", "Liberia", "Lituania", "Luxemburgo", "Letonia", "Libia", "Marruecos", "Moldavia", 
            "Montenegro", "Madagascar", "República de Macedonia", "Birmania", "Mongolia", "Macao", "Islas Marianas del Norte", "Martinica", "Malta", "Mauricio", "Maldivas", "México", 
            "Malasia", "Nueva Caledonia", "Nicaragua", "Países Bajos", "Noruega", "Nepal", "Nueva Zelanda", "Omán", "Panamá", "Perú", "Polinesia Francesa", "Filipinas", "Pakistán",
            "Polonia", "San Pedro y Miquelón", "Puerto Rico", "Palestina", "Portugal", "Paraguay", "Catar", "Reunión", "Rumanía", "Serbia", "Rusia", "Arabia Saudita", "Sudán",
            "Suecia", "Singapur", "Eslovenia", "Eslovaquia", "Senegal", "Surinam", "El Salvador", "Siria", "Tailandia", "Tayikistán", "Túnez", "Turquía", "Trinidad y Tobago", 
            "Taiwán", "Ucrania", "Reino Unido", "Estados Unidos", "Uruguay", "Uzbekistán", "Venezuela", "Islas Vírgenes de los Estados Unidos", "Vietnam", "Sudáfrica"]
        }, 
        {
            "id": "capitals",
            "name": "Capitales de países",
            "words": ["Abu Dabi", "Abuya", "Acra", "Adís Abeba", "Amán", "Andorra la Vieja", "Ankara", "Antananarivo", "Apia", "Argel", "Asjabad", "Asmara", "Astaná", "Asunción",
            "Atenas", "Babane y Lobamba", "Bagdad", "Bakú", "Bamako", "Bandar Seri Begawan", "Bangkok", "Bangui", "Banjul", "Basseterre", "Beirut", "Belgrado", "Belmopán", "Berlín",
            "Berna", "Biskek", "Bisáu", "Bloemfontein", "Bogotá", "Brasilia", "Bratislava", "Brazzaville", "Bridgetown", "Bruselas", "Bucarest", "Budapest", "Buenos Aires" ,"Camberra",
            "Caracas", "Castries", "Chisináu", "Ciudad de Guatemala", "Ciudad de México", "Ciudad Del Cabo", "Ciudad del Vaticano", "Colombo", "Conakri", "Copenhague", "Cotonú", "Daca",
            "Dakar", "Damasco", "Dili", "Dodoma", "Doha", "Dublín", "Dusambé", "El Cairo", "Ereván", "Estocolmo", "Fongafale", "Freetown", "Gaborone", "Georgetown", "Gitega", "Hanói",
            "Harare", "Helsinki", "Honiara", "Islamabad", "Jartum", "Jerusalén", "Kabul", "Kampala", "Katmandú", "Kiev", "Kigali", "Kingston", "Kingstown", "Kinsasa", "Kuala Lumpur",
            "Kuwait", "La Habana", "La Valeta", "Libreville", "Lilongüe", "Lima", "Lisboa", "Liubliana", "Lomé", "Londres", "Luanda", "Lusaka", "Luxemburgo", "Madrid", "Majuro",
            "Malabo", "Malé", "Managua", "Manama", "Manila", "Maputo", "Mascate", "Maseru", "Melekeok", "Minsk", "Mogadiscio", "Monrovia", "Montevideo", "Moroni", "Moscú", "Mónaco",
            "Naipyidó", "Nairobi", "Nassau", "Niamey", "Nicosia", "Nom Pen", "Nuakchot", "Nueva Delhi", "Nukualofa", "Oslo", "Ottawa", "Palikir", "Panamá", "Paramaribo", "París",
            "Pekín", "Pionyang", "Podgorica", "Port Moresby", "Port Vila", "Port-Louis", "Porto Novo", "Praga", "Praia", "Pretoria", "Puerto España", "Puerto Príncipe", "Quito",
            "Rabat", "Reikiavik", "Riad", "Riga", "Roma", "Roseau", "Saint George", "Saint John", "San José", "San Marino", "San Salvador", "Santiago de Chile", "Santo Domingo", 
            "Santo Tomé", "Saná", "Sarajevo", "Seúl", "Singapur", "Skopie", "Sofía", "Sri Jayewardenepura", "Sucre", "Suva", "Tallin", "Tarawa", "Taskent", "Tegucigalpa", "Teherán",
            "Tiflis", "Timbu", "Tirana", "Tokio", "Trípoli", "Túnez", "Uagadugú", "Ulán Bator", "Vaduz", "Varsovia", "Victoria", "Viena", "Vientián", "Vilna", "Washington DC",
            "Wellington", "Windhoek", "Yakarta", "Yamena", "Yamusukro", "Yaren", "Yaundé", "Yibuti", "Yuba", "Zagreb", "Ámsterdam"]
        },
        {
            "id": "animals",
            "name": "Animales",
            "words": ["Abeja melífera", "Abejaruco esmeralda", "Abejorro", "Acara azul eléctrico", "Ajolote", "Albatros", "Alce", "Almeja gigante", "Anguila eléctrica", 
            "Anguila morena", "Antílope", "Ardilla", "Armadillo", "Armiño", "Ascidias", "Ave del paraíso", "Avestruz", "Avispa", "Avispón asiático gigante", "Avoceta", "Águila",
            "Babosa de mar", "Babuino", "Ballena azul", "Barbo", "Barracuda", "Bisonte", "Buitre", "Burro", "Busardo ratonero", "Búfalo", "Búho chico", "Búho nival", "Caballito de mar",
            "Caballo", "Cabra", "Cachalote común", "Caimán", "Calamar", "Camaleón", "Camarón", "Camello", "Cangrejo", "Cangrejo herradura", "Canguro", "Capibara", "Caracal", "Caracol",
            "Castor", "Casuario", "Cebra", "Cebú", "Cerdo", "Cerdo hormiguero", "Cetia japonés", "Chacal", "Chimpancé", "Chinchilla", "Ciempiés", "Ciervo", "Cigüeña", "Cisne",
            "Civeta africana", "Civeta de las palmeras común", "Civeta malaya", "Coatí de cola anillada", "Cobaya", "Cochinilla de la humedad", "Cocodrilo", "Codorniz común", "Colibrí",
            "Colimbo grande", "Comadreja", "Conejo", "Coral", "Coyote", "Cucaracha", "Cárabo común", "Cíclido", "Delfín", "Demonio de Tasmania", "Dientes de sable", "Dingo", "Dodo",
            "Dragón de agua asiático", "Dragón de agua australiano", "Dragón de Komodo", "Dragón de mar foliáceo", "Dugongo", "Dólar de plata", "Elefante", "Emperador púrpura", "Emú común",
            "Erizo", "Erizo de mar", "Escarabajo", "Escorpión", "Esponjas de mar", "Espátula rosada", "Estrella de mar", "Facóquero común", "Faetón", "Faisán", "Flamenco", "Foca común",
            "Frailecillo común", "Fregata", "Gallina", "Gallina de Guinea", "Gallineta común", "Gamba", "Ganso", "Garza", "Gato doméstico", "Gavial", "Gecko", "Glotón", "Gorila", "Gorrión",
            "Grulla", "Guacamayo", "Guepardo", "Guppy", "Halcón", "Hiena", "Hipopótamo", "Hormiga", "Hurón", "Hámster", "Ibis", "Iguana", "Impala", "Indri", "Jabalí", "Jaguar", "Jirafa",
            "Kakapo", "Kiwi", "Koala", "Labridae", "Lagarto", "Lagarto caimán del norte", "Langosta", "Lechuza común", "Leopardo", "León", "León marino", "Libélula", "Liebre", "Lince",
            "Llama", "Lobo", "Loro", "Luchador de Siam", "Lucio", "Luciérnaga", "Lémur", "Manatí", "Mandril", "Mangosta", "Mantarraya", "Mapache", "Mariposa", "Mariquita",
            "Martín pescador", "Medusa", "Milpiés", "Mirlo común", "Mofeta", "Molly", "Mono", "Morsa", "Mosca común", "Mula", "Murciélago", "Murciélago vampiro", "Musaraña",
            "Numbat", "Nutria", "Ocelote", "Orangután", "Orca", "Ornitorrinco", "Oropéndola", "Oruga", "Oso", "Ostra", "Oveja", "Pantera negra", "Pato", "Pavo", "Pelícano",
            "Peramélido", "Percebe", "Perezoso", "Periquito común", "Perro", "Pez cirujano", "Pez disco", "Pez gato", "Pez globo", "Pez león", "Pez mariposa", "Pez Payaso",
            "Pez Ángel", "Pingüino", "Piraña", "Polilla", "Pollo", "Proteo", "Puercoespín", "Pulpo", "Puma", "Pájaro carpintero", "Quetzal", "Rana africana de uñas",
            "Rana cohete rayada", "Rana comestible", "Rana dardo venenosa", "Rana de Darwin", "Rana europea común", "Rana excavadora", "Rana toro", "Rana verde centroeuropea",
            "Ranas arbóreas", "Ranita monte Iberia", "Rata", "Ratón común", "Raya", "Reno", "Rinoceronte", "Rorcual", "Ruiseñor", "Salamandra", "Saltamontes", "Sapo africano",
            "Sapo común", "Sapo de caña", "Sapo de vientre de fuego", "Sapo pata de pala", "Sepia", "Ser humano", "Serpiente", "Sula patiazul", "Suricato", "Tejón", "Termita",
            "Tiburón", "Tiburón mielga", "Tigre", "Topo", "Tortuga", "Tucán", "Tucán pico iris", "Urraca común", "Vaca", "Vaca marina de Steller", "Viuda negra", "Wombat", "Xifóforo",
            "Yarará común", "Zapatero", "Zarigüeya", "Zorro", "Zorro Polar"]
        },
        {
            "id": "games",
            "name": "Juegos",
            "words": ["Metal Gear Solid", "Grand Theft Auto", "Assassin's Creed", "The Last of Us", "Resident Evil", "Call of Duty", "Batman", "Persona", "Red Dead Redemption", "Red Faction",
            "FIFA", "Fallen Legion", "Just Dance", "Pro Evolution Soccer", "Shovel Knight", "Revenant Saga", "King's Quest", "Final Fantasy", "Doodle Devil", "Minecraft", "Doodle Kingdom",
            "Skylanders", "Monster Jam", "Hopping Dinos", "Ghost of Tsushima", "Hollow Knight", "Cyberpunk", "Deep Down", "Beyond Good and Evil", "Wild", "Dead Island", "Granblue Fantasy",
            "Biomutant", "Marvel's Avengers", "The Elder Scrolls", "Edge of Eternity", "Elden Ring", "Tales of Arise", "Project Awakening", "Fortnite", "Apex Legends", "Lost Soul Aside",
            "Kingdom Under Fire", "Skull and Bones", "Overcooked", "Dead or Alive", "Gods and Monsters", "Watch Dogs", "Dragon Age", "GhostWire", "Dying Light", "Twin Mirror", "Crash Bandicoot",
            "Little Devil Inside", "Project Eve", "Without Memory", "Visage", "Psychonauts", "Knights of Light", "Animal Crossing", "Bravely Default", "Xenoblade Chronicles", "Paper Mario",
            "Super Mario World", "Super Smash Bros", "Super Mario Bros", "Super Mario Party", "The Legend of Zelda", "Thief Simulator", "Moto Rush GT", "Uno", "Monopoly", "Dragon Ball Xenoverse",
            "Super Mario Maker", "Tetris", "Dark Souls", "Pac-Man", "Kirby's Adventure", "Galaga", "Killer Instinct", "Space Invaders", "Diablo", "Guitar Hero", "Clone Hero", "Arkanoid",
            "Super Contra", "World of Warcraft", "League of Legends", "Street Fighter", "The King of Fighters", "Mortal Kombat", "Metal Slug", "Luigi's Mansion", "Super Mario Odyssey",
            "Donkey Kong Country", "Bomberman", "Valorant"]
        },
        {
            "id": "names",
            "name": "Nombres",
            "words": ["Aaron", "Abigail", "Abril", "Adriana", "Adrián", "Agustina", "Agustín", "Aitana", "Alba", "Alejandra", "Alejandro", "Alexa", "Alexander", "Alexandra", "Allison",
            "Álvaro", "Amanda", "Ana", "Ana María", "Ana Sofía", "Andrea", "Andrés", "Ángel", "Angela", "Anthony", "Antonella", "Antonia", "Antonio", "Ariana", "Ashley", "Axel", "Bautista",
            "Benjamín", "Bianca", "Briana", "Bruno", "Bárbara", "Camila", "Candela", "Carla", "Carlos", "Carolina", "Catalina", "Christopher", "Clara", "Claudia", "Constanza", "Cristian",
            "Cristóbal", "César", "Daniel", "Daniela", "David", "Delfina", "Diana", "Diego", "Dylan", "Eduardo", "Elena", "Emanuel", "Emilia", "Emiliano", "Emilio", "Emily", "Emma", "Erick",
            "Esteban", "Felipe", "Fernanda", "Fernando", "Florencia", "Francisco", "Fátima", "Gabriel", "Gabriela", "Gael", "Gonzalo", "Guadalupe", "Guillermo", "Génesis", "Hugo", "Ian",
            "Ignacio", "Iker", "Isaac", "Isabel", "Isabella", "Isidora", "Iván", "Javier", "Jazmín", "Jerónimo", "Jesús", "Joaquín", "Jonathan", "Jorge", "Josefina", "Joshua", "José", "Juan",
            "Juan Andrés", "Juan David", "Juan José", "Juan Manuel", "Juan Pablo", "Juan Sebastián", "Juanita", "Julia", "Juliana", "Julieta", "Julián", "Kevin", "Kimberly", "Laura",
            "Laura Sofía", "Leonardo", "Lola", "Luca", "Lucas", "Luciana", "Luciano", "Lucía", "Luis", "Luna", "Manuel", "Manuela", "Marcos", "Mariana", "Mario", "Marta", "Martina", "Martín",
            "María", "María Camila", "María Fernanda", "María José", "Mateo", "Matthew", "Matías", "Mauricio", "Máximo", "Maximiliano", "Melanie", "Melissa", "Micaela", "Michelle", "Miguel", "Miguel Ángel",
            "Miranda", "Monserrat", "Morena", "Mía", "Naomí", "Natalia", "Natalie", "Nicole", "Nicolás", "Oscar", "Pablo", "Paloma", "Paola", "Paula", "Paulin", "Pedro", "Pilar", "Rafael",
            "Rebeca", "Regina", "Renata", "Ricardo", "Roberto", "Rodrigo", "Sabrina", "Samantha", "Samuel", "Santiago", "Santino", "Sara", "Sebastián", "Sergio", "Simón", "Sofía", "Stephanie",
            "Thiago", "Tomás", "Valentina", "Valentín", "Valeria", "Valerie", "Vanessa", "Vicente", "Victoria", "Ximena", "Zoe"]
        },
        {
            "id": "animes",
            "name": "Animes",
            "words": ["Toriko", "Dragon Ball", "Boku no Hero", "Zero no Tsukaima", "Blend S", "Ansatsu Kyoushitsu", "Sword Art Online", "ZombieLand Saga", "Nanbaka", "Naruto", "One Piece",
            "Fairy Tail", "Tokyo Ghoul", "Hunter x Hunter", "Shingeky no Kyojin", "Full Metal Alchemist", "Bleach", "Mirai Nikki", "Nanatsu no Taizai", "Inazuma Eleven", "Kaito Kid",
            "Kuma Miko", "Sailor Moon", "Pokemon", "Saint Seiya", "Yu-Gi-Oh", "Jojo's Bizarre Adventure", "Monster Musume no Iru Nichijou", "High School DxD", "Watamote", "Kakegurui",
            "Gintama", "Black Clover", "Kenichi", "Detective Conan", "Charlotte", "Kono Subarashii Sekai ni Shukufuku Wo", "Shin Chan", "Prison School", "One Punch Man", "Shimoneta",
            "Noragami", "Himegoto", "To Love Ru", "Aho Girl", "Idaten Jump", "Danganronpa", "Youjo senki", "Kobayashi", "Nisekoi", "Hataraku Saibou", "No Game No Life", "Rokunedashi Majutsu",
            "Asobi Asobase", "Parasyte", "Code Geass", "Gabriel DropOut", "Darling in the Franxx", "Ore ga Suki", "Deadman Wonderland", "Goblin Slayer", "Cybercat Kurochan", "Toradora",
            "Hataraku mao Sama", "Ao no Exorcist", "Terra Rormars", "Mob Psycho", "Tensei Shitara Slime Datta Ken", "Blood Lad", "Dies Irae", "Grappler Baki", "Rokunedashi", "Overlord",
            "Medaka Box Abnormal", "Mondaiji Tachi", "Kishuku Gakkou no Juliet", "Erased", "Eromanga Sensei", "Kill la Kill", "Little Witch Academia", "Re:Zero", "Karakai Jouzu no Takagi San",
            "Devilman Crybaby", "Blood C", "Gotoubun no Hanayome", "Dororo", "Tate no Yuusha", "Selector Spread Wixoss", "Endro", "Kaguya-sama wa Kokurasetai", "Yakusoku no Neverland",
            "Ueno-san wa Bukiyou", "Bunny Girl Senpai", "Berserk", "Boogiepop wa Warawanai", "Domestic na Kanojo", "Fate", "Kyoukai no Kanata", "Watashi ni Tenshi", "One Room", "Akane Iro ni Somaru Saka",
            "Another", "Gunjou no Magmel", "Boku Dake ga Inai Machi", "Satsuriko no Tenshi", "Black Bullet", "Kenja no Mago", "Magi the Labyrinth", "Sakamoto Desu Ga", "Inuyashiki", "Oniai",
            "Otaku Teacher", "Araburu Kisetsu", "Kimetsu no Yaiba", "Isekai Quartet", "Hitoribocchi", "Fairy Gone", "Durarara", "Radiant", "Dr Stone", "Arifureta Shokugyou", "Tsuuyou Kougeki ga Zentai",
            "Tejina Senpai", "Machikado Mazoku", "New Game", "Dumbbell Nan Kilo Moteru", "Enen no Shouboutai", "Vinland Saga", "Sounan Desu Ka", "Isekai Cheat Magician", "Nakanohito Genome",
            "Akatsuki no Yona", "Beastars", "Chuubyou Gekihatsu Boy", "Kandagawa Jet Girls", "Mugen no Juunin", "No Guns Life", "Null Peta", "Rifle is Beautiful", "Shinchou Yuusha",
            "Val x Love", "Kanata no Astra", "Rakudai Kishi no Calvary", "Kiss Him Not Me", "Happy Sugar Life", "Kokoro Connect", "Dorohedoro", "Gleipnir", "Hatena Illusion",
            "Ishuzoku Reviewers", "Jibaku Shounen Hanako-kun", "Kyokou Suiri", "Magia Record: Mahou Shoujo Madoka Magica", "Majutsushi Orphen Hagure Tabi", "Murenase! Seton Gakuen",
            "Mushoku Tensei: Isekai Ittara Honki Dasu", "PET", "Plunderer", "Somali to Mori no Kamisama", "Uzumaki", "Mahou Shoujo Site", "Tsudedure Children", "Sora no Otoshimono",
            "Lucky Star", "Elfen Lied", "Clannad", "Hellsing", "Jashin-Chan DropKick", "Kakushigoto", "Otome Game no Hametsu Flag Shika Nai", "Princess Connect! Re:Dive",
            "Netsuzou Trap", "Tower of God"]
        },
        {
            "id": "colours",
            "name": "Colores",
            "words": ["Acero", "Agua", "Aguacate", "Agua Marina", "Albaricoque", "Almagre", "Almendra", "Aluminio", "Amaranto", "Amarillo", "Amatista", "Ámbar", "Anaranjado", "Ante",
            "Antracita", "Añil", "Arena", "Asfalto", "Aureolina", "Avellana", "Azabache", "Azafrán", "Azul", "Azur", "Banana", "Barbecho", "Begonia", "Beis", "Beige", "Berenjena", "Bermejo",
            "Bermellón", "Bígaro", "Bistre", "Blanco", "Borgoña", "Bronce", "Bronceado", "Burdeo", "Bordó", "Café", "Calabaza", "Calipso", "Café con leche cósmico", "Camello", "Canela",
            "Caoba", "Caqui", "Caramelo", "Carbón", "Cardena", "Cardenillo", "Cardo", "Carmesí", "Carmín", "Carne", "Cartujo", "Castaña", "Celeste", "Ceniza", "Cerceta", "Cereza", "Cerúleo",
            "Cetrino", "Champán", "Chartreuse", "Chocolate", "Cian", "Ciruela", "Cobrizo", "Concha", "Conchevino", "Coral", "Cordobán", "Corinto", "Crema", "Cuarzo", "Damasco", "Dorado",
            "Durazno", "Ébano", "Elefante", "Encaje Antiguo", "Escarlata", "Espinaca", "Esmeralda", "Fandango", "Feldrau", "Frambuesa", "Fucsia", "Gamusa", "Geranio", "Glauco", "Grafito",
            "Grana", "Granate", "Gris", "Gualda", "Gules", "Guinda", "Gutagamba", "Habano", "Herrumbre", "Hígado", "Hueso", "Humo", "Índigo", "Iris", "Jazmín", "Junquillo", "Jade", "Kalua",
            "Kaki", "Kiwi", "Lacre", "Lapislázuli", "Latón", "Lava", "Lavanda", "León", "Lila", "Lima", "Limón", "Lino", "Lirio", "Llama", "Lombarda", "Lúcuma", "Magenta", "Maíz", "Malaquita",
            "Malva", "Mamey", "Mandarina", "Marfil", "Marrón", "Melocotón", "Melón", "Menta", "Miel", "Morado", "Mostaza", "Musgo", "Naranja", "Negro", "Níquel", "Nogal", "Ocaso", "Ocre",
            "Oro", "Orquídea", "Oliva", "Palo rosa", "Palta", "Pardo", "Perla", "Perú", "Pistacho", "Pizarra", "Plata", "Plateado", "Plomo", "Porcelana", "Porráceo", "Puerro", "Púrpura",
            "Purpúreo", "Quermes", "Rojo", "Rosa", "Rosado", "Rubí", "Rufo", "Salmón", "Sangría", "Secuoya", "Sepia", "Siena", "Sinople", "Té Verde", "Teja", "Tomate", "Torcaza", "Topo",
            "Trigo", "Turquí", "Turquesa", "Ultramar", "Uva", "Vainilla", "Verde", "Verdete", "Verdín", "Verdigris", "Vino", "Vinotinto", "Violeta", "Violín", "Viridián", "Wasabi", "Wengué",
            "Xanadú", "Xántico", "Yema", "Yeso", "Zafiro", "Zanahoria", "Zinc", "Transparente"]
        },
        {
            "id": "jobs",
            "name": "Trabajos",
            "words": ["Abogada", "Abogado", "Académica", "Académico", "Adjunta", "Adjunto", "Administrador", "Administradora", "Administrativa", "Administrativo", "Afilador", "Afiladora",
            "Agricultor", "Agricultora", "Agrónoma", "Agrónomo", "Alarife", "Albañil", "Alergista", "Alergóloga", "Alergólogo", "Alfarera", "Alfarero", "Alguera", "Alguero", "Almacenera",
            "Almacenero", "Almacenista", "Anatomista", "Anestesista", "Anestesióloga", "Anestesiólogo", "Antologista", "Antologista", "Antropóloga", "Antropólogo", "Aparapita", "Arabista",
            "Arabista", "Archivera", "Archivero", "Arenera", "Arenero", "Armera", "Armero", "Arqueóloga", "Arqueólogo", "Arquitecta", "Arquitecto", "Arrumbador", "Arrumbadora", "Asesor",
            "Asesora", "Asistenta", "Asistente", "Astrofísica", "Astrofísico", "Astróloga", "Astrólogo", "Astrónoma", "Astrónomo", "Atleta", "Autor", "Autora", "Auxiliar", "Avicultor",
            "Avicultora", "Bacterióloga", "Bacteriólogo", "Barbera", "Barbero", "Barrendera", "Barrendero", "Bedel", "Bedela", "Bibliotecaria", "Bibliotecario", "Bibliógrafa", "Bibliógrafo",
            "Biofísica", "Biofísico", "Bioquímica", "Bioquímico", "Biógrafa", "Biógrafo", "Bióloga", "Biólogo", "Bombera", "Bombero", "Botánica", "Botánico", "Bromatóloga", "Bromatólogo",
            "Camarera", "Camarero", "Camionera", "Camionero", "Canceróloga", "Cancerólogo", "Cantera", "Cantero", "Cardióloga", "Cardiólogo", "Carpintera", "Carpintero", "Cartógrafa",
            "Cartógrafo", "Casamentera", "Casamentero", "Castrador", "Castradora", "Catedrática", "Catedrático", "Cazador", "Cazadora", "Cerera", "Cerero", "Chófer", "Cirujana", "Cirujano",
            "Citóloga", "Citólogo", "Climatóloga", "Climatólogo", "Cocinera", "Cocinero", "Codirector", "Codirectora", "Colchonera", "Colchonero", "Comadrona", "Comadrón", "Consejera",
            "Consejero", "Conserje", "Conservador", "Conservadora", "Coordinador", "Coordinadora", "Cosmógrafa", "Cosmógrafo", "Cosmóloga", "Cosmólogo", "Criminalista", "Cristalera",
            "Cristalero", "Cronóloga", "Cronólogo", "Decana", "Decano", "Decorador", "Decoradora", "Defensor", "Defensora", "Delegada", "Delegado", "Delineante", "Demógrafa", "Demógrafo",
            "Dentista", "Dermatóloga", "Dermatólogo", "Dibujante", "Directiva", "Directivo", "Director", "Directora", "Dirigente", "Doctor", "Doctora", "Documentalista", "Economista",
            "Ecóloga", "Ecólogo", "Educador", "Educadora", "Egiptóloga", "Egiptólogo", "Electricista", "Endocrinóloga", "Endocrinólogo", "Enfermera", "Enfermero", "Entomóloga", "Entomólogo",
            "Enóloga", "Enólogo", "Epidemióloga", "Epidemiólogo", "Escritor", "Escritora", "Especialista", "Espeleóloga", "Espeleólogo", "Estadista", "Estadística", "Estadístico", "Etimologista",
            "Etimóloga", "Etimólogo", "Etnógrafa", "Etnógrafo", "Etnóloga", "Etnólogo", "Etóloga", "Etólogo", "Examinador", "Examinadora", "Facultativa", "Facultativo", "Farmacéutica",
            "Farmacéutico", "Farmacóloga", "Farmacólogo", "Filóloga", "Filólogo", "Filósofa", "Filósofo", "Fiscal", "Fisioterapeuta", "Fisióloga", "Fisiólogo", "Fonetista", "Fontanera",
            "Fontanero", "Foníatra", "Foníatra", "Fonóloga", "Fonólogo", "Forense", "Fotógrafa", "Fotógrafo", "Funcionaria", "Funcionario", "Física", "Físico", "Gemóloga", "Gemólogo",
            "Genetista", "Geobotánica", "Geodesta", "Geodesto", "Geofísica", "Geofísico", "Geomántica", "Geomántico", "Geoquímica", "Geoquímico", "Gerenta", "Gerente", "Geriatra",
            "Gerontóloga", "Gerontólogo", "Gestor", "Gestora", "Geógrafa", "Geógrafo", "Geóloga", "Geólogo", "Geómetra", "Grabador", "Grabadora", "Graduada social", "Graduado social",
            "Grafóloga", "Grafólogo", "Gramática", "Gramático", "Hematóloga", "Hematólogo", "Hepatóloga", "Hepatólogo", "Herrera", "Herrero", "Hidrogeóloga", "Hidrogeólogo", "Hidrógrafa",
            "Hidrógrafo", "Hidróloga", "Hidrólogo", "Higienista", "Hispanista", "Historiador", "Historiadora", "Homeópata", "Informática", "Informático", "Ingeniera", "Ingeniera técnica",
            "Ingeniero", "Ingeniero técnico", "Inmunóloga", "Inmunólogo", "Inspector", "Inspectora", "Interina", "Interino", "Interventor", "Interventora", "Investigador", "Investigadora",
            "Jardinera", "Jardinero", "Jefa", "Jefe", "Joyera", "Joyero", "Juez", "Jueza", "Latinista", "Lector", "Lectora", "Letrada", "Letrado", "Lexicógrafa", "Lexicógrafo", "Lexicóloga",
            "Lexicólogo", "Leñador", "Leñadora", "Licenciada", "Licenciado", "Limpiabotas", "Lingüista", "Logopeda", "Maestra", "Maestro", "Manicurista", "Matemática", "Matemático", "Matrona",
            "Matrón", "Mecánica", "Mecánico", "Medica", "Medico", "Meteoróloga", "Meteorólogo", "Microbiológica", "Microbiológico", "Microcirujana", "Microcirujano", "Micóloga", "Micólogo",
            "Mimógrafa","Mimógrafo","Modista","Monitor","Monitora","Musicóloga","Musicólogo","Naturópata","Nefróloga","Nefrólogo","Neumóloga","Neumólogo","Neuroanatomista","Neurobióloga",
            "Neurobiólogo","Neurocirujana","Neurocirujano","Neuroembrióloga","Neuroembriólogo","Neurofisióloga","Neurofisiólogo","Neuróloga","Neurólogo","Nutróloga","Nutrólogo","Oceanógrafa",
            "Oceanógrafo","Odontóloga","Odontólogo","Oficial","Oficiala","Oficinista","Oftalmóloga","Oftalmólogo","Oncóloga","Oncólogo","Óptica","Óptico","Optometrista","Ordenanza",
            "Orfebrera","Orfebrero","Orientador","Orientadora","Ornitóloga","Ornitólogo","Ortopédica","Ortopédico","Ortopedista","Osteóloga","Osteólogo","Osteópata","Otorrinolaringóloga",
            "Otorrinolaringólogo","Paleobióloga","Paleobiólogo","Paleobotánica","Paleobotánico","Paleógrafa","Paleógrafo","Paleóloga","Paleólogo","Paleontóloga","Paleontólogo","Palliri",
            "Pastor","Patóloga","Patólogo","Pedagoga","Pedagogo","Pediatra","Pedicura","Pedicuro","Peletera","Peletero","Peluquera","Peluquero","Periodista","Perita","Perito","Pescador",
            "Pescadora","Pintor","Pintora","Piscicultor","Piscicultora","Podóloga","Podólogo","Policia","Portera","Portero","Prehistoriador","Prehistoriadota","Presidenta","Presidente",
            "Proctóloga","Proctólogo","Profesor","Profesora","Programador","Programadora","Prostituta","Prostituto","Protésica","Protésico","Proveedor","Proveedora","Psicoanalista",
            "Psicofísica","Psicofísico","Psicóloga","Psicólogo","Psicopedagoga","Psicopedagogo","Psicoterapeuta","Psiquiatra","Publicista","Publicitaria","Publicitario","Puericultor",
            "Puericultora","Química","Químico","Quiropráctica","Quiropráctico","Radioastrónoma","Radioastrónomo","Radiofonista","Radióloga","Radiólogo","Radiotécnica","Radiotécnico",
            "Radiotelefonista","Radiotelegrafista","Radioterapeuta","Rector","Rectora","Repostera","Repostero","Rotulista","Sanitaria","Sanitario","Secretaria","Secretario","Sexóloga",
            "Sexólogo","Sirvienta","Sirviente","Sismóloga","Sismólogo","Socióloga","Sociólogo","Subdelegada","Subdelegado","Subdirector","Subdirectora","Subsecretaria","Subsecretario",
            "Taxidermista","Técnica","Técnico","Telefonista","Teóloga","Teólogo","Terapeuta","Tintorera","Tintorero","Tocoginecóloga","Tocoginecólogo","Tocóloga","Tocólogo","Tonelera",
            "Tonelero","Tornera","Tornero","Toxicóloga","Toxicólogo","Trabajador doméstico","Trabajadora doméstica","Traductor","Traductora","Transcriptor","Transcriptora","Traumatóloga",
            "Traumatólogo","Tutor","Tutora","Uróloga","Urólogo","Veterinaria","Veterinario","Vicedecana","Vicedecano","Vicedirector","Vicedirectora","Vicegerenta","Vicegerente",
            "Vicepresidenta","Vicepresidente","Vicerrector","Vicerrectora","Vicesecretaria","Vicesecretario","Viróloga","Virólogo","Viticultor","Viticultora","Vulcanóloga","Vulcanólogo",
            "Waterpolista","Windsurfista","Xérografa","Xérografo","Xilofonista","Xilógrafa","Xilógrafo","Zapatera","Zapatero","Zoóloga","Zoólogo","Zootécnica","Zootécnico"]
        },
        {
            "id": "pokemon",
            "name": "Pokémon",
            "words": ["Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard","Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree","Weedle","Kakuna","Beedrill",
            "Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate","Spearow","Fearow","Ekans","Arbok","Pikachu","Raichu","Sandshrew","Sandslash","Nidoran","Nidorina","Nidoqueen","Nidoran",
            "Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat","Venomoth",
            "Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck","Mankey","Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop",
            "Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel","Geodude","Graveler","Golem","Ponyta","Rapidash","Slowpoke","Slowbro","Magnemite","Magneton",
            "Farfetch’d","Doduo","Dodrio","Seel","Dewgong","Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode",
            "Exeggcute","Exeggutor","Cubone","Marowak","Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan","Horsea","Seadra",
            "Goldeen","Seaking","Staryu","Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee","Vaporeon","Jolteon",
            "Flareon","Porygon","Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew","Chikorita",
            "Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados",
            "Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom","Marill","Azumarill","Sudowoodo","Politoed",
            "Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown","Wobbuffet","Girafarig",
            "Pineco","Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa","Ursaring","Slugma","Magcargo","Swinub",
            "Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour","Houndoom","Kingdra","Phanpy","Donphan","Porygon2","Stantler","Smeargle","Tyrogue",
            "Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar","Lugia","Ho-Oh","Celebi","Treecko","Grovyle","Sceptile",
            "Torchic","Combusken","Blaziken","Mudkip","Marshtomp","Swampert","Poochyena","Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Lotad","Lombre",
            "Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper","Ralts","Kirlia","Gardevoir","Surskit","Masquerain","Shroomish","Breloom","Slakoth","Vigoroth",
            "Slaking","Nincada","Ninjask","Shedinja","Whismur","Loudred","Exploud","Makuhita","Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye","Mawile","Aron","Lairon","Aggron",
            "Meditite","Medicham","Electrike","Manectric","Plusle","Minun","Volbeat","Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord","Numel","Camerupt",
            "Torkoal","Spoink","Grumpig","Spinda","Trapinch","Vibrava","Flygon","Cacnea","Cacturne","Swablu","Altaria","Zangoose","Seviper","Lunatone","Solrock","Barboach","Whiscash",
            "Corphish","Crawdaunt","Baltoy","Claydol","Lileep","Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Kecleon","Shuppet","Banette","Duskull","Dusclops","Tropius",
            "Chimecho","Absol","Wynaut","Snorunt","Glalie","Spheal","Sealeo","Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Beldum","Metang",
            "Metagross","Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys","Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape",
            "Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew","Roserade","Cranidos","Rampardos",
            "Shieldon","Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen","Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos","Gastrodon","Ambipom","Drifloon","Drifblim",
            "Buneary","Lopunny","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor","Bronzong","Bonsly","MimeJr.","Happiny","Chatot","Spiritomb","Gible",
            "Gabite","Garchomp","Munchlax","Riolu","Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Finneon","Lumineon","Mantyke","Snover",
            "Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z",
            "Gallade","Probopass","Dusknoir","Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin",
            "Arceus","Victini","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott","Dewott","Samurott","Patrat","Watchog","Lillipup","Herdier","Stoutland","Purrloin",
            "Liepard","Pansage","Simisage","Pansear","Simisear","Panpour","Simipour","Munna","Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola","Boldore","Gigalith",
            "Woobat","Swoobat","Drilbur","Excadrill","Audino","Timburr","Gurdurr","Conkeldurr","Tympole","Palpitoad","Seismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Venipede",
            "Whirlipede","Scolipede","Cottonee","Whimsicott","Petilil","Lilligant","Basculin","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan","Maractus","Dwebble","Crustle","Scraggy",
            "Scrafty","Sigilyph","Yamask","Cofagrigus","Tirtouga","Carracosta","Archen","Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita",
            "Gothitelle","Solosis","Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck","Emolga","Karrablast","Escavalier","Foongus",
            "Amoonguss","Frillish","Jellicent","Alomomola","Joltik","Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinklang","Tynamo","Eelektrik","Eelektross","Elgyem","Beheeyem",
            "Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal","Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon","Golett","Golurk",
            "Pawniard","Bisharp","Bouffalant","Rufflet","Braviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon","Larvesta","Volcarona","Cobalion","Terrakion",
            "Virizion","Tornadus","Thundurus","Reshiram","Zekrom","Landorus","Kyurem","Keldeo","Meloetta","Genesect","Chespin","Quilladin","Chesnaught","Fennekin","Braixen","Delphox",
            "Froakie","Frogadier","Greninja","Bunnelby","Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa","Vivillon","Litleo","Pyroar","Flabebe","Floette","Florges",
            "Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Honedge","Doublade","Aegislash","Spritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle",
            "Barbaracle","Skrelp","Dragalge","Clauncher","Clawitzer","Helioptile","Heliolisk","Tyrunt","Tyrantrum","Amaura","Aurorus","Sylveon","Hawlucha","Dedenne","Carbink","Goomy",
            "Sliggoo","Goodra","Klefki","Phantump","Trevenant","Pumpkaboo","Gourgeist","Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion",
            "Rowlet","Dartrix","Decidueye","Litten","Torracat","Incineroar","Popplio","Brionne","Primarina","Pikipek","Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug",
            "Vikavolt","Crabrawler","Crabominable","Oricorio","Cutiefly","Ribombee","Rockruff","Lycanroc","Wishiwashi","Mareanie","Toxapex","Mudbray","Mudsdale","Dewpider","Araquanid",
            "Fomantis","Lurantis","Morelull","Shiinotic","Salandit","Salazzle","Stufful","Bewear","Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod",
            "Sandygast","Palossand","Pyukumuku","Type: Null","Silvally","Minior","Komala","Turtonator","Togedemaru","Mimikyu","Bruxish","Drampa","Dhelmise","Jangmo-o","Hakamo-o","Kommo-o",
            "TapuKoko","TapuLele","TapuBulu","TapuFini","Cosmog","Cosmoem","Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana","Guzzlord","Necrozma",
            "Magearna","Marshadow","Poipole","Naganadel","Stakataka","Blacephalon","Zeraora","Meltan","Melmetal","Grookey","Thwackey","Rillaboom","Scorbunny","Raboot","Cinderace","Sobble",
            "Drizzile","Inteleon","Blipbug","Dottler","Orbeetle","Rookidee","Corvisquire","Corviknight","Skwovet","Greedent","Nickit","Thievul","Galarian Zigzagoon","Galarian Linoone",
            "Obstagoon","Wooloo","Dubwool","Chewtle","Drednaw","Yamper","Boltund","Gossifleur","Eldegoss","Sizzlipede","Centiskorch","Rolycoly","Carkol","Coalossal","Arrokuda","Barraskewda",
            "Galarian Meowth","Perrserker","Milcery","Alcremie","Applin","Flapple","Appletun","Galarian Farfetch'd","Sirfetch'd","Galarian Stunfisk","Galarian Corsola","Cursola","Impidimp",
            "Morgrem","Grimmsnarl","Hatenna","Hattrem","Hatterene","Galarian Weezing","Cufant","Copperajah","Cramorant","Toxel","Toxtricity","Silicobra","Sandaconda","Galarian Yamask",
            "Runerigus","Galarian Ponyta","Galarian Rapidash","Sinistea","Polteageist","Indeedee","Morpeko","Falinks","Snom","Frosmoth","Clobbopus","Grapploct","Pincurchin","Galarian Mr. Mime",
            "Mr. Rime","Galarian Darumaka","Galarian Darmanitan","Stonjourner","Eiscue","Duraludon","Dracozolt","Actrozolt","Dracovish","Arctovish","Dreepy","Drakloak","Dragapult","Zacian",
            "Zamazenta","Eternatus","Zarude","Alolan Meowth","Alolan Persian","Alolan Sandshrew","Alolan Sandslash","Alolan Vulpix","Alolan Ninetales","Alolan Exeggutor","Alolan Marowak",
            "Alolan Raichu","Alolan Rattata","Alolan Raticate","Alolan Grimer","Alolan Muk","Alolan Diglett","Alolan Dugtrio"]
        },
        {
            "id": "surnames",
            "name": "Apellidos",
            "words": ["Acosta","Acuña","Aguilar","Aguirre","Agustín","Ahumada","Alanis","Alarcón","Alayón","Alcázar","Alcocer","Alfaro","Almendárez","Altamirano","Álvarez","Alzate","Amador",
            "Anaya","Argüelles","Arjona","Arriaga","Arrollo","Ayala","Baca","Báez","Baños","Barba","Barrera","Barrientos","Barriga","Bastida","Batalla","Bautista","Bazán","Becerra","Becerril",
            "Bello","Beltrán","Benítez","Bernal","Bolaños","Bonilla","Borges","Bustamante","Busto","Caballero","Cabeza","Cabrera","Cadenas","Caldera","Calderón","Calleja","Calles","Camacho",
            "Camareno","Camarillo","Campos","Cárdenas","Cardoso","Carranza","Carrillo","Carvajal","Carvallo","Casas","Castellanos","Castañeda","Cepeda","Cerda","Cervantes","Céspedes",
            "Cevallos","Cevedo","Chávez","Chavira","Cisneros","Collado","Cordero","Cornejo","Correa","Corro","Cuéllar","Cuervo","Cuesta","Cuevas","Daniel","Darío","Dávila","De Aguilar",
            "De Alba","De la Cruz","De la Cuesta","De la Fuente","De la Rosa","Del Castillo","Doblado","Domínguez","Donato","Dorado","Duarte","Dueñas","Echeverría","Elizondo","Enríquez",
            "Escalante","Escamilla","Escobar","Escobedo","Escoto","Escovar","Espino","Esquivel","Estévez","Estrada","Estrella","Fábregas","Falcón","Farías","Fernández","Ferreira","Ferrer",
            "Fierro","Figueras","Flores","Fonseca","Fraga","Frías","Fuentes","Funez","Gaitán","Galán","Galeano","Galeno","Galindo","Gallegos","Galván","Gamboa","Gámez","García","Garrido",
            "Gavilán","Gayoso","Gaytán","Gillén","Godines","Gómez","Góngora","Granada","Granados","Grijalba","Guardado","Guardiola","Guerrero","Guillén","Gutiérrez","Guzmán","Heredia",
            "Hernández","Herrera","Hidalgo","Hierro","Huerta","Hurtado","Ibáñez","Ibarra","Icaza","Iglesias","Infante","Ivañez","Izquierdo","Jara","Jaramillo","Jerano","Jiménez","Juárez",
            "Junco","Jurado","Lacayo","Lafuente","Lagos","Lagunal","Lamas","Lández","Larios","Lastreto","Lázaro","Leandro","Lemus","Leyva","Linares","Lines","Lira","Lizano","Llano","Lobo",
            "Lombardo","López","Loredo","Lorio","Losada","Lozano","Lucas","Lugo","Luna","Macedo","Machado","Macías","Maduro","Magallón","Maldonado","Maltés","Mantilla","Manuel",
            "Manzanal","Manzano","Marcías","Marrero","Marroquí","Martí","Martínez","Mateo","Matías","Maurer","Medrano","Medina","Mendoza","Mejía","Mena","Meneses","Merazo","Meza",
            "Mijares","Milanés","Minas","Molina","Molleda","Moneda","Monge","Montalbán","Montalvo","Montecinos","Montero","Montes","Montiel","Morillo","Moscoa","Munera","Murillo",
            "Naranjo","Navaro","Navarrete","Navarro","Nieto","Noble","Noguera","Noriega","Novales","Novo","Novoa","Núñez","Obellón","Obregón","Ocampo","Ochoa","Ordóñez","Olguín",
            "Olivar","Olivares","Olivera","Olmeda","Olmedo","Olmo","Ordóñez","Orozco","Ortega","Ortiz","Oseda","Osorio","Ospino","Otero","Oviedo","Ozuno","Pacheco","Padilla","Páez",
            "Palacio","Paladino","Palazuelos","Palomar","Palomino","Paniagua","Pantoja","Parado","Páramo","Pardo","Paredes","Parra","Pastor","Pastrana","Patiño","Paz","Pedroza","Pena",
            "Peña","Peralta","Peraza","Perdomo","Pineda","Pino","Plácido","Ponce","Portillo","Prada","Prieto","Puente","Quesada","Quezada","Quevedo","Quijada","Quijano","Quintana",
            "Quintanilla","Quiroga","Quiroz","Ramírez","Ramón","Ramos","Rangel","Real","Redondo","Restrepo","Reyes","Rivas","Rivera","Roble","Robles","Rojas","Roldán","Román","Romero",
            "Rosales","Rosas","Rovira","Rubín","Rubio","Rueda","Ruiz","Sabín","Sáenz","Sagel","Sala","Salas","Salazar","Salcedo","Saldaña","Saldivar","Salinas","Salmón","Salvado",
            "Samper","Sánchez","Sandino","Sandoval","Santiago","Santos","Sardinas","Sarmiento","Saucedo","Savala","Seballos","Sedano","Segura","Silva","Sol","Solana","Solé","Soler",
            "Solís","Somoza","Sorio","Sotelo","Soto","Sotomayor","Soza","Suárez","Tablada","Talavera","Tames","Taracena","Tedesco","Tejada","Tobar","Torre","Torres","Torrente","Tovar",
            "Travieso","Trejos","Treminio","Triguero","Troncoso","Triviño","Triviños","Trujillo","Valdés","Valdiva","Valencia","Valentín","Valenzuela","Vales","Valle","Vallejo","Vanegas",
            "Varela","Varga","Vargas","Vásquez","Vega","Vela","Velarde","Velasco","Velásquez","Venegas","Ventura","Verti","Vidal","Villallobos","Villar","Villareal","Villas","Villaseñor",
            "Villeda","Vivas","Vivero","Vívez","Wade","Wagner","Wallach","Waller","Walsh","Walters","Walterson","Waltz","Wang","Xavier","Ximenes","Ximenez","Xura","Xuarez","Yagüe","Yáñez",
            "Yanguas","Yangüe","Yániz","Yarto","Ybañez","Ybar","Ybarguen","Ybarguengoitia","Ybarguren","Ybarlucea","Ybarra","Ybarreche","Ybarrola","Ybieta","Yborra","Ycaza","Ydiondo",
            "Ydoyaga","Yébenes","Yebra","Yenlamos","Yerro","Yeste","Yeza","Yglesia","Ylarraz","Ylleta","Ymar","Ymas","Ymaz","Ynarra","Ynaz","Ynchaurraga","Ynchausti","Ynda","Yndabere","Ynés",
            "Ynsausti","Ynurritegui","Ynza","Yoldi","Yparrea","Ypenza","Ypina","Yquierdo","Yrazabal","Yrazola","Yrazuzta","Yribar","Yrigoyen","Yrisarri","Yrure","Yruretagoiena","Yrurzun",
            "Ysasi","Ysern","Ysusi","Yturain","Yturbe","Yturburua","Yturralde","Yturriaga","Yturzaeta","Yubero","Yus","Yusta","Yuste","Yza","Yzaguirre","Yzaguirrre","Yzeta","Yzquierdo",
            "Yztueta","Yzurieta","Zabala","Zabaleta","Zabalo","Zabalza","Zafra","Zaga","Zahínos","Zájara","Zalduegui","Zamacona","Zamarriego","Zambrano","Zamora","Zandueta","Zapata","Zapater",
            "Zapatero","Zapico","Zaplana","Zaragoza","Zarate","Zarauz","Zarazua","Zarca","Zarco","Zarra","Zarragoicoechea","Zarza","Zarzalejo","Zarzoso","Zatarain","Zatoro","Zatoya","Zavala",
            "Zavaleta","Zavalo","Zazu","Zearra","Zeballos","Zelada","Zelaia","Zelaya","Zenarruza","Zenarruzabeitia","Zenarruzaveitia","Zengotita","Zenita","Zenitagoia","Zereceda","Zerezo",
            "Zidras","Zoales","Zobarán","Zoco","Zoracain","Zorita","Zorrilla","Zozaya","Zuaso","Zuasua","Zuazo","Zuazola","Zuazola-Cigorraga","Zuazua","Zubeldia","Zubia","Zubiete","Zubillaga",
            "Zubiria","Zubizarreta","Zuburruti","Zufía","Zufiaur","Zufidia","Zuheros","Zulaica","Zuluaga","Zulueta","Zumeta","Zuriaga","Zuriarrain","Zurita","Zurrón","Zurutuza","Zuzuarregi"]
        },
        {
            "id": "minecraft",
            "name": "Minecraft",
            "words": ["Bat","Bee","Blaze","Cat","Cave Spider","Chicken","Chicken Jockey","Cod","Cow","Creeper","Dolphin","Donkey","Drowned","Elder Guardian","Ender Dragon","Enderman",
            "Endermite","Evoker","Fox","Ghast","Giant","Guardian","Hoglin","Horse","Husk","Illusioner","Iron Golem","Killer Bunny","Llama","Magma Cube","Mooshroom","Mule","Ocelot","Panda",
            "Parrot","Phantom","Pig","Piglin","Pillager","Polar Bear","Pufferfish","Rabbit","Ravager","Salmon","Sheep","Shulker","Silverfish","Skeleton","Skeleton Horse","Skeleton Horseman",
            "Slime","Snow Golem","Spider","Spider Jockey","Squid","Stray","Strider","Tropical Fish","Turtle","Vex","Villager","Vindicator","Wandering Trader","Witch","Wither",
            "Wither Skeleton","Wolf","Zoglin","Zombie","Zombie Horse","Zombie Pigman","Zombie Villager"]
        }];
    };
