module.exports.valid_countries = [
    "AD", "AE", "AG", "AL", "AM", "AR", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE", 
    "BG", "BH", "BM", "BN", "BO", "BR", "BS", "BY", "BZ", "CA", "CF", "CH", "CI", "CL", "CN", 
    "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "DZ", "EC", "EE", "EG", "ER", "ES", "EU", "FI", 
    "FO", "FR", "GE", "GF", "GG", "GI", "GL", "GP", "GR", "GT", "GU", "GY", "HK", "HN", "HR", 
    "HU", "ID", "IE", "IL", "IM", "IN", "IQ", "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", 
    "KG", "KH", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LT", "LU", "LV", "LY", 
    "MA", "MD", "ME", "MG", "MK", "MM", "MN", "MO", "MP", "MQ", "MT", "MU", "MV", "MX", "MY", 
    "NC", "NI", "NL", "NO", "NP", "NZ", "OM", "PA", "PE", "PF", "PH", "PK", "PL", "PM", "PR", 
    "PS", "PT", "PY", "QA", "RE", "RO", "RS", "RU", "SA", "SD", "SE", "SG", "SI", "SK", "SN", 
    "SR", "SV", "SY", "TH", "TJ", "TN", "TR", "TT", "TW", "UA", "UK", "US", "UY", "UZ", "VE", 
    "VI", "VN", "ZA"
];

module.exports.countries_es = {
    "AD": ":flag_ad: Andorra", "AE": ":flag_ae: Emiratos Árabes Unidos", "AG": ":flag_ag: Antigua y Barbuda",
    "AL": ":flag_al: Albania", "AM": ":flag_am: Armenia", "AR": ":flag_ar: Argentina", "AT": ":flag_at: Austria",
    "AU": ":flag_au: Australia", "AW": ":flag_aw: Aruba", "AX": ":flag_ax: Islas Åland", "AZ": ":flag_az: Azerbaiyán",
    "BA": ":flag_ba: Bosnia y Herzegovina", "BB": ":flag_bb: Barbados", "BD": ":flag_bd: Bangladés", "BE": ":flag_be: Bélgica",
    "BG": ":flag_bg: Bulgaria", "BH": ":flag_bh: Baréin", "BM": ":flag_bm: Bermudas", "BN": ":flag_bn: Brunéi", "BO": ":flag_bo: Bolivia",
    "BR": ":flag_br: Brasil", "BS": ":flag_bs: Bahamas", "BY": ":flag_by: Bielorrusia", "BZ": ":flag_bz: Belice", "CA": ":flag_ca: Canadá",
    "CF": ":flag_cf: República Centroafricana", "CH": ":flag_ch: Suiza", "CI": ":flag_ci: Costa de Marfil", "CL": ":flag_cl: Chile",
    "CN": ":flag_cn: China", "CO": ":flag_co: Colombia", "CR": ":flag_cr: Costa Rica", "CY": ":flag_cy: Chipre", "CZ": ":flag_cz: República Checa",
    "DE": ":flag_de: Alemania", "DK": ":flag_dk: Dinamarca", "DO": ":flag_do: República Dominicana", "DZ": ":flag_dz: Argelia", "EC": ":flag_ec: Ecuador",
    "EE": ":flag_ee: Estonia", "EG": ":flag_eg: Egipto", "ER": ":flag_er: Eritrea", "ES": ":flag_es: España", "EU": ":flag_eu: Unión Europea",
    "FI": ":flag_fi: Finlandia", "FO": ":flag_fo: Islas Feroe", "FR": ":flag_fr: Francia", "GE": ":flag_ge: Georgia", "GF": ":flag_gf: Guayana Francesa",
    "GG": ":flag_gg: Guernsey", "GI": ":flag_gi: Gibraltar", "GL": ":flag_gl: Groenlandia", "GP": ":flag_gp: Guadalupe", "GR": ":flag_gr: Grecia",
    "GT": ":flag_gt: Guatemala", "GU": ":flag_gu: Guam", "GY": ":flag_gy: Guyana", "HK": ":flag_hk: Hong Kong", "HN": ":flag_hn: Honduras",
    "HR": ":flag_hr: Croacia", "HU": ":flag_hu: Hungría", "ID": ":flag_id: Indonesia", "IE": ":flag_ie: Irlanda", "IL": ":flag_il: Israel",
    "IM": ":flag_im: Isla de Man", "IN": ":flag_in: India", "IQ": ":flag_iq: Irak", "IR": ":flag_ir: Irán", "IS": ":flag_is: Islandia",
    "IT": ":flag_it: Italia", "JE": ":flag_je: Jersey", "JM": ":flag_jm: Jamaica", "JO": ":flag_jo: Jordania", "JP": ":flag_jp: Japón",
    "KE": ":flag_ke: Kenia", "KG": ":flag_kg: Kirguistán", "KH": ":flag_kh: Camboya", "KR": ":flag_kr: Corea del Sur", "KW": ":flag_kw: Kuwait",
    "KZ": ":flag_kz: Kazajistán", "LA": ":flag_la: Laos", "LB": ":flag_lb: Líbano", "LC": ":flag_lc: Santa Lucía", "LI": ":flag_li: Liechtenstein",
    "LK": ":flag_lk: Sri Lanka", "LR": ":flag_lr: Liberia", "LT": ":flag_lt: Lituania", "LU": ":flag_lu: Luxemburgo", "LV": ":flag_lv: Letonia",
    "LY": ":flag_ly: Libia", "MA": ":flag_ma: Marruecos", "MD": ":flag_md: Moldavia", "ME": ":flag_me: Montenegro", "MG": ":flag_mg: Madagascar",
    "MK": ":flag_mk: República de Macedonia", "MM": ":flag_mm: Birmania", "MN": ":flag_mn: Mongolia", "MO": ":flag_mo: Macao", "MP": ":flag_mp: Islas Marianas del Norte",
    "MQ": ":flag_mq: Martinica", "MT": ":flag_mt: Malta", "MU": ":flag_mu: Mauricio", "MV": ":flag_mv: Maldivas", "MX": ":flag_mx: México", "MY": ":flag_my: Malasia",
    "NC": ":flag_nc: Nueva Caledonia", "NI": ":flag_ni: Nicaragua", "NL": ":flag_nl: Países Bajos", "NO": ":flag_no: Noruega", "NP": ":flag_np: Nepal",
    "NZ": ":flag_nz: Nueva Zelanda", "OM": ":flag_om: Omán", "PA": ":flag_pa: Panamá", "PE": ":flag_pe: Perú", "PF": ":flag_pf: Polinesia Francesa",
    "PH": ":flag_ph: Filipinas", "PK": ":flag_pk: Pakistán", "PL": ":flag_pl: Polonia", "PM": ":flag_pm: San Pedro y Miquelón", "PR": ":flag_pr: Puerto Rico",
    "PS": ":flag_ps: Palestina", "PT": ":flag_pt: Portugal", "PY": ":flag_py: Paraguay", "QA": ":flag_qa: Catar", "RE": ":flag_re: Reunión",
    "RO": ":flag_ro: Rumanía", "RS": ":flag_rs: Serbia", "RU": ":flag_ru: Rusia", "SA": ":flag_sa: Arabia Saudita", "SD": ":flag_sd: Sudán",
    "SE": ":flag_se: Suecia", "SG": ":flag_sg: Singapur", "SI": ":flag_si: Eslovenia", "SK": ":flag_sk: Eslovaquia", "SN": ":flag_sn: Senegal",
    "SR": ":flag_sr: Surinam", "SV": ":flag_sv: El Salvador", "SY": ":flag_sy: Siria", "TH": ":flag_th: Tailandia", "TJ": ":flag_tj: Tayikistán",
    "TN": ":flag_tn: Túnez", "TR": ":flag_tr: Turquía", "TT": ":flag_tt: Trinidad y Tobago", "TW": ":flag_tw: Taiwán", "UA": ":flag_ua: Ucrania",
    "UK": ":flag_gb: Reino Unido", "US": ":flag_us: Estados Unidos", "UY": ":flag_uy: Uruguay", "UZ": ":flag_uz: Uzbekistán", "VE": ":flag_ve: Venezuela",
    "VI": ":flag_vi: Islas Vírgenes de los Estados Unidos", "VN": ":flag_vn: Vietnam", "ZA": ":flag_za: Sudáfrica"
};
