module.exports.valid_countries = [
    "AD", "AE", "AG", "AL", "AM", "AR", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE", 
    "BG", "BH", "BM", "BN", "BO", "BR", "BS", "BY", "BZ", "CA", "CF", "CH", "CI", "CL", "CN", 
    "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "DZ", "EC", "EE", "EG", "ER", "ES", "EU", "FI", 
    "FO", "FR", "GE", "GF", "GG", "GI", "GL", "GP", "GR", "GT", "GU", "GY", "HK", "HN", "HR", 
    "HU", "ID", "IE", "IL", "IM", "IN", "IQ", "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", 
    "KG", "KH", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LT", "LU", "LV", "LY", 
    "MA", "MD", "ME", "MG", "MK", "MM", "MN", "MO", "MP", "MQ", "MT", "MU", "MV", "MX", "MY", 
    "NC", "NI", "NL", "NO", "NP", "NZ", "OM", "PA", "PE", "PF", "PH", "PK", "PL", "PM", "PR", 
    "PS", "PT", "PY", "QA", "RE", "RO", "RS", "RU", "SA", "SD", "SE", "SG", "SI", "SK", "SN", 
    "SR", "SV", "SY", "TH", "TJ", "TN", "TR", "TT", "TW", "UA", "UK", "US", "UY", "UZ", "VE", 
    "VI", "VN", "ZA"
];

module.exports.aliases = {
    "AD": "AD", "Andorra": "AD", "Principat d'Andorra": "AD",
    "AE": "AE", "United Arab Emirates": "AE", "Emiratos Arabes Unidos": "AE", "Emirates": "AE", "الإمارات‎": "AE", "الإمارات العربية المتحدة": "AE", "UAE": "AE", "EAU": "AE",
    "AF": "AF", "Afghanistan": "AF", "Afganistan": "AF", "افغانستان": "AF",
    "AG": "AG", "Antigua and Barbuda": "AG", "Antigua y Barbuda": "AG",
    "AI": "AI", "Anguilla": "AI",
    "AL": "AL", "Albania": "AL", "Shqipëria": "AL", "Shqipëri": "AL",
    "AM": "AM", "Armenia": "AM", "Հայաստան": "AM", "Հայաստանի Հանրապետություն": "AM",
    "AO": "AO", "Angola": "AO", "República de Angola": "AO",
    "AR": "AR", "Argentina": "AR",
    "AS": "AS", "American Samoa": "AS", "Samoa Americana": "AS", "Amerika Sāmoa": "AS",
    "AT": "AT", "Austria": "AT", "Republik Österreich": "AT", "Österreich": "AT",
    "AU": "AU", "Australia": "AU",
    "AW": "AW", "Aruba": "AW",
    "AX": "AX", "Aland Islands": "AX", "Islas Aland": "AX", "Aland": "AX", "Aland Island": "AX",
    "AZ": "AZ", "Azerbaijan": "AZ", "Azerbaiyan": "AZ", "Azərbaycan": "AZ", "Azərbaycan Respublikası": "AZ",
    "BA": "BA", "Bosnia and Herzegovina": "BA", "Bosnia y Herzegovina": "BA", "Bosna i Hercegovina": "BA", "Босна и Херцеговина": "BA",
    "BB": "BB", "Barbados": "BB",
    "BD": "BD", "Bangladesh": "BD", "Banglades": "BD", "বাংলাদেশ": "BD",
    "BE": "BE", "Belgium": "BE", "Belgica": "BE", "België": "BE", "Belgique": "BE", "Belgien": "BE",
    "BF": "BF", "Burkina Faso": "BF",
    "BG": "BG", "Bulgaria": "BG", "България": "BG",
    "BH": "BH", "Bahrain": "BH", "Bahrein": "BH", "Barein": "BH", "البحرين": "BH",
    "BI": "BI", "Burundi": "BI",
    "BJ": "BJ", "Benin": "BJ",
    "BM": "BM", "Bermuda": "BM", "Bermudas": "BM",
    "BN": "BN", "Brunei": "BN", "بروني دارالسلام": "BN",
    "BO": "BO", "Bolivia": "BO",
    "BQ": "BQ", "Bonaire": "BQ", "Boneiru": "BQ",
    "BR": "BR", "Brazil": "BR", "Brasil": "BR",
    "BS": "BS", "Bahamas": "BS", 
    "BT": "BT", "Bhutan": "BT", "Butan": "BT",
    "BW": "BW", "Botswana": "BW", "Botsuana": "BW",
    "BY": "BY", "Belarus": "BY", "Bielorrusia": "BY", "Беларусь": "BY",
    "BZ": "BZ", "Belize": "BZ", "Belice": "BZ",
    "CA": "CA", "Canada": "CA",
    "CC": "CC", "Cocos Island": "CC", "Isla del Coco": "CC",
    "CD": "CD", "Democratic Republic of the Congo": "CD", "DR Congo": "CD", "RD Congo": "CD", "DRC": "CD", "DROC": "CD",
    "CF": "CF", "Central African Republic": "CF", "Republica Centroafricana": "CF", "Ködörösêse tî Bêafrîka": "CF", "République centrafricaine": "CF",
    "CG": "CG", "Republic of the Congo": "CG", "République du Congo": "CG", "Repubilika ya Kôngo": "CG", "Congo Republic": "CG", "República del Congo": "CG",
    "CH": "CH", "Switzerland": "CH", "Suiza": "CH",
    "CI": "CI", "Cote d'Ivoire": "CI", "Ivory Coast": "CI", "Costa de Marfil": "CI",
    "CK": "CK", "The Cook Islands": "CK", "Cook Islands": "CK", "Kūki 'Āirani": "CK",
    "CL": "CL", "Chile": "CL",
    "CM": "CM", "Cameroon": "CM", "Camerun": "CM", "Cameroun": "CM",
    "CN": "CN", "China": "CN", "中国": "CN", "Zhōngguó": "CN",
    "CO": "CO", "Colombia": "CO",
    "CR": "CR", "Costa Rica": "CR",
    "CU": "CU", "Cuba": "CU",
    "CV": "CV", "Cape Verde": "CV", "Cabo Verde": "CV",
    "CW": "CW", "Curacao": "CW", "Curazao": "CW", "Curasao": "CW", "Kòrsou": "CW",
    "CX": "CX", "Christmas Island": "CX", "Isla de Navidad": "CX", "圣诞岛": "CX", "Pulau Krismas": "CX",
    "CY": "CY", "Cyprus": "CY", "Chipre": "CY", "Kıbrıs": "CY", "Κύπρος": "CY", 
    "CZ": "CZ", "Czechia": "CZ", "Czech Republic": "CZ", "Republica Checa": "CZ", "Chequia": "CZ", "Česko": "CZ", "Česká republika": "CZ",
    "DE": "DE", "Germany": "DE", "Alemania": "DE", "Deutschland": "DE",
    "DJ": "DJ", "Djibouti": "DJ", "Yibuti": "DJ", "جيبوتي": "DJ",
    "DK": "DK", "Denmark": "DK", "Dinamarca": "DK", "Danmark": "DK",
    "DM": "DM", "Dominica": "DM", "Dominique": "DM",
    "DO": "DO", "Dominican Republic": "DO", "Republica Dominicana": "DO",
    "DZ": "DZ", "Algeria": "DZ", "Argelia": "DZ", "الجزائر": "DZ",
    "EC": "EC", "Ecuador": "EC",
    "EE": "EE", "Estonia": "EE", "Eesti": "EE",
    "EG": "EG", "Egypt": "EG", "Egipto": "EG", "مصر": "EG",
    "EH": "EH", "Western Sahara": "EH", "Sahara Occidental": "EH", "الصحراء الغربية": "EH", "Taneẓroft Tutrimt": "EH",
    "ER": "ER", "Eritrea": "ER",
    "ES": "ES", "Spain": "ES", "España": "ES",
    "ET": "ET", "Ethiopia": "ET", "Etiopia": "ET", "ኢትዮጵያ": "ET",
    "FI": "FI", "Finland": "FI", "Finlandia": "FI", "Suomi": "FI",
    "FJ": "FJ", "Fiji": "FJ", "Fiyi": "FJ", "फ़िजी": "FJ",
    "FK": "FK", "Falkland Islands": "FK", "The Falkland Islands": "FK", "Islas Malvinas": "FK",
    "FM": "FM", "Micronesia": "FM", "Federated States of Micronesia": "FM", "FSM": "FM",
    "FO": "FO", "Faroe Islands": "FO", "Islas Feroe": "FO", "Føroyar": "FO", "Færøerne": "FO",
    "FR": "FR", "France": "FR", "Francia": "FR",
    "GA": "GA", "Gabon": "GA",
    "GB": "GB", "United Kingdom": "GB", "Reino Unido": "GB",
    "GD": "GD", "Grenada": "GD", "Granada": "GD", "Gwenad": "GD",
    "GE": "GE", "Georgia": "GE", "საქართველო": "GE",
    "GG": "GG", "Guernsey": "GG", "Guernesey": "GG",
    "GH": "GH", "Ghana": "GH",
    "GI": "GI", "Gibraltar": "GI",
    "GL": "GL", "Greenland": "GL", "Groenlandia": "GL", "Grønland": "GL", "Kalaallit Nunaat": "GL",
    "GM": "GM", "Gambia": "GM", "The Gambia": "GM",
    "GN": "GN", "Guinea": "GN", "Guinée": "GN",
    "GQ": "GQ", "Equatorial Guinea": "GQ", "Guinea Ecuatorial": "GQ", "Guinée équatoriale": "GQ", "Guiné Equatorial": "GQ",
    "GR": "GR", "Greece": "GR", "Grecia": "GR", "Ελλάδα": "GR",
    "GT": "GT", "Guatemala": "GT",
    "GU": "GU", "Guam": "GU", "Guåhån": "GU",
    "GW": "GW", "Guinea-Bissau": "GW", "Guinea-Bisau": "GW", "Guiné-Bissau": "GW",
    "GY": "GY", "Guyana": "GY",
    "HK": "HK", "Hong Kong": "HK", "香港": "HK",
    "HN": "HN", "Honduras": "HN",
    "HR": "HR", "Croatia": "HR", "Croacia": "HR", "Hrvatska": "HR",
    "HT": "HT", "Haiti": "HT", "Ayiti": "HT",
    "HU": "HU", "Hungary": "HU", "Hungría": "HU", "Magyarország": "HU",
    "IC": "IC", "Islas Canarias": "IC", "Canary Islands": "IC",
    "ID": "ID", "Indonesia": "ID",
    "IE": "IE", "Ireland": "IE", "Irlanda": "IE", "Éire": "IE",
    "IL": "IL", "Israel": "IL", "ישראל": "IL", "إسرائيل": "IL",
    "IM": "IM", "Isle of Man": "IM", "Isla de Man": "IM", "Ellan Vannin": "IM",
    "IN": "IN", "India": "IN", "भारत": "IN",
    "IO": "IO", "British Indian Ocean Territory": "IO", "The British Indian Ocean Territory": "IO", "BIOT": "IO",
    "IQ": "IQ", "Iraq": "IQ", "Irak": "IQ", "العراق": "IQ",
    "IR": "IR", "Iran": "IR", "ایران": "IR",
    "IS": "IS", "Iceland": "IS", "Islandia": "IS", "Ísland": "IS",
    "IT": "IT", "Italy": "IT", "Italia": "IT",
    "JE": "JE", "Jersey": "JE", "Jèrri": "JE",
    "JM": "JM", "Jamaica": "JM", "Jumieka": "JM",
    "JO": "JO", "Jordan": "JO", "Jordania": "JO", "الأردنّ": "JO",
    "JP": "JP", "Japan": "JP", "Japon": "JP", "日本": "JP",
    "KE": "KE", "Kenya": "KE", "Kenia": "KE",
    "KG": "KG", "Kyrgyzstan": "KG", "Kirguistán": "KG", "Кыргызстан": "KG", "Киргизия": "KG",
    "KH": "KH", "Cambodia": "KH", "Camboya": "KH", "ព្រះរាជាណាចក្រកម្ពុជា": "KH", "កម្ពុជា": "KH",
    "KI": "KI", "Kiribati": "KI",
    "KM": "KM", "Comoros": "KM", "Comoras": "KM", "Comores": "KM", "الاتحاد القمري": "KM", "The Comoros": "KM",
    "KN": "KN", "Saint Kitts and Nevis": "KN",
    "KP": "KP", "North Korea": "KP", "Corea del Norte": "KP", "조선민주주의인민공화국": "KP", "北韓": "KP",
    "KR": "KR", "South Korea": "KR", "Corea del Sur": "KR", "대한민국": "KR",
    "KW": "KW", "Kuwait": "KW", "دولة الكويت": "KW",
    "KY": "KY", "Cayman Islands": "KY", "Islas Caiman": "KY",
    "KZ": "KZ", "Kazakhstan": "KZ", "Kazajistán": "KZ", "Қазақстан": "KZ", "Казахстан": "KZ",
    "LA": "LA", "Laos": "LA", "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ": "LA", "ປະເທດລາວ": "LA",
    "LB": "LB", "Lebanon": "LB", "Libano": "LB", "لبنان": "LB",
    "LC": "LC", "Saint Lucia": "LC", "Santa Lucía": "LC", "Sainte-Lucie": "LC",
    "LI": "LI", "Liechtenstein": "LI",
    "LK": "LK", "Sri Lanka": "LK", "ශ්‍රී ලංකා": "LK", "இலங்கை": "LK",
    "LR": "LR", "Liberia": "LR",
    "LS": "LS", "Lesotho": "LS", "Lesoto": "LS",
    "LT": "LT", "Lithuania": "LT", "Lituania": "LT", "Lietuva": "LT",
    "LU": "LU", "Luxembourg": "LU", "Luxemburgo": "LU", "Lëtzebuerg": "LU", "Luxemburg": "LU",
    "LV": "LV", "Latvia": "LV", "Letonia": "LV", "Latvijas Republika": "LV",
    "LY": "LY", "Libya": "LY", "Libia": "LY", "Libu": "LY", "ليبيا": "LY",
    "MA": "MA", "Morocco": "MA", "Marruecos": "MA", "المغرب": "MA", "ⵎⵓⵔⴰⴽⵓⵛ": "MA",
    "MC": "MC", "Monaco": "MC", "Mu̍negu": "MC", "Mónegue": "MC",
    "MD": "MD", "Moldova": "MD", "Republic of Moldova": "MD", "Republica Moldova": "MD", "Moldavia": "MD",
    "ME": "ME", "Montenegro": "ME", "Crna Gora": "ME", "Црна Гора": "ME",
    "MG": "MG", "Madagascar": "MG", "Madagasikara": "MG",
    "MH": "MH", "Marshall Islands": "MH", "Islas Marshall": "MH", "Aolepān Aorōkin Ṃajeḷ": "MH",
    "MK": "MK", "North Macedonia": "MK", "Macedonia del Norte": "MK", "Македонија": "MK",
    "ML": "ML", "Mali": "ML", 
    "MM": "MM", "Myanmar": "MM", "Birmania": "MM", "မြန်မာ": "MM", "Burma": "MM",
    "MN": "MN", "Mongolia": "MN", "Монгол Улс": "MN", "Mongol Uls": "MN",
    "MO": "MO", "Macao": "MO", "Macau": "MO", "澳門": "MO", "澳门": "MO",
    "MP": "MP", "Northern Mariana Islands": "MP", "The Northern Mariana Islands": "MP",
    "MQ": "MQ", "Martinique": "MQ", "Martinica": "MQ",
    "MR": "MR", "Mauritania": "MR", "موريتانيا": "MR", "Mauritanie": "MR", "Moritani": "MR", "Gànnaar": "MR", "Murutaane": "MR",
    "MS": "MS", "Montserrat": "MS",
    "MT": "MT", "Malta": "MT",
    "MU": "MU", "Mauritius": "MU", "Mauricio": "MU", "Maurice": "MU", "Moris": "MU",
    "MV": "MV", "Maldives": "MV", "Maldivas": "MV", "ދިވެހިރާއްޖެ": "MV",
    "MW": "MW", "Malawi": "MW", "Malaui": "MW",
    "MX": "MX", "Mexico": "MX",
    "MY": "MY", "Malaysia": "MY", "Malasia": "MY", "مليسيا": "MY",
    "MZ": "MZ", "Mozambique": "MZ", "Moçambique": "MZ",
    "NA": "NA", "Namibia": "NA", "Namibië": "NA",
    "NE": "NE", "Niger": "NE", "The Niger": "NE",
    "NF": "NF", "Norfolk Island": "NF", "Isla Norfolk": "NF", "Norf'k Ailen": "NF",
    "NG": "NG", "Nigeria": "NG",
    "NI": "NI", "Nicaragua": "NI",
    "NL": "NL", "Netherlands": "NL", "Países Bajos": "NL", "Nederland": "NL", "The Netherlands": "NL",
    "NO": "NO", "Norway": "NO", "Noruega": "NO", "Norge": "NO", "Noreg": "NO", "Norga": "NO", "Vuodna": "NO", "Nöörje": "NO",
    "NP": "NP", "Nepal": "NP", "नेपाल": "NP",
    "NR": "NR", "Nauru": "NR", "Naoero": "NR",
    "NU": "NU", "Niue": "NU",
    "NZ": "NZ", "New Zealand": "NZ", "Nueva Zelanda": "NZ", "Aotearoa": "NZ",
    "OM": "OM", "Oman": "OM", "عمان": "OM",
    "PA": "PA", "Panama": "PA",
    "PE": "PE", "Peru": "PE",
    "PF": "PF", "French Polynesia": "PF", "Polinesia Francesa": "PF", "Polynésie Française": "PF", "Porinetia Farani": "PF",
    "PG": "PG", "Papua New Guinea": "PG", "Papua Nueva Guinea": "PG", "Papua Niugini": "PG", "Papua Niu Gini": "PG",
    "PH": "PH", "Philippines": "PH", "Filipinas": "PH", "Pilipinas": "PH", "The Philippines": "PH",
    "PK": "PK", "Pakistan": "PK", "پاکستان": "PK",
    "PL": "PL", "Poland": "PL", "Polonia": "PL", "Polska": "PL",
    "PN": "PN", "Pitcairn Islands": "PN", "Pitcairn": "PN", "Pitkern Ailen": "PN", "Islas Pitcairn": "PN",
    "PR": "PR", "Puerto Rico": "PR",
    "PS": "PS", "Palestine": "PS", "فلسطين": "PS", "دولة فلسطين": "PS", "Palestina": "PS",
    "PT": "PT", "Portugal": "PT",
    "PW": "PW", "Palau": "PW", "Palaos": "PW", "Beluu er a Belau": "PW", "パラオ": "PW",
    "PY": "PY", "Paraguay": "PY", "Paraguái": "PY",
    "QA": "QA", "Qatar": "QA", "Catar": "QA", "قطر‎": "QA",
    "RO": "RO", "Romania": "RO", "Rumania": "RO",
    "RS": "RS", "Serbia": "RS", "Србија": "RS", "Srbija": "RS",
    "RU": "RU", "Russia": "RU", "Rusia": "RU", "Росси́я": "RU",
    "RW": "RW", "Rwanda": "RW", "Ruanda": "RW", "u Rwanda": "RW",
    "SA": "SA", "Saudi Arabia": "SA", "Arabia Saudita": "SA", "السعودية": "SA",
    "SB": "SB", "Solomon Islands": "SB", "Islas Salomón": "SB", 
    "SC": "SC", "Seychelles": "SC",
    "SD": "SD", "Sudan": "SD", "السودان": "SD", "as-Sūdān": "SD",
    "SE": "SE", "Sweden": "SE", "Suecia": "SE", "Sverige": "SE",
    "SG": "SG", "Singapore": "SG", "Singapur": "SG", "Singapura": "SG",
    "SI": "SI", "Slovenia": "SI", "Eslovenia": "SI", "Slovenija": "SI",
    "SK": "SK", "Slovakia": "SK", "Eslovaquia": "SK", "Slovensko": "SK",
    "SL": "SL", "Sierra Leone": "SL", "Sierra Leona": "SL", "Salone": "SL",
    "SM": "SM", "San Marino": "SM",
    "SN": "SN", "Senegal": "SN", "Senegaal": "SN",
    "SO": "SO", "Somalia": "SO", "Soomaaliya": "SO", "الصومال": "SO",
    "SR": "SR", "Suriname": "SR", "Surinam": "SR",
    "SS": "SS", "South Sudan": "SS", "Sudan del Sur": "SS", "Sudan Kusini": "SS",
    "ST": "ST", "Sao Tome and Principe": "ST", "Santo Tome y Principe": "ST", "Saint Thomas and Prince": "ST",
    "SV": "SV", "El Salvador": "SV",
    "SX": "SX", "Sint Maarten": "SX",
    "SY": "SY", "Syria": "SY", "Siria": "SY", "سوريا": "SY",
    "SZ": "SZ", "Eswatini": "SZ", "Swaziland": "SZ", "Suazilandia": "SZ", "Esuatini": "SZ",
    "TC": "TC", "Turks and Caicos Islands": "TC", "The Turks and Caicos Islands": "TC",
    "TD": "TD", "Chad": "TD", "Tchad": "TD", "تشاد": "TD",
    "TG": "TG", "Togo": "TG",
    "TH": "TH", "Thailand": "TH", "Tailandia": "TH", "ประเทศไทย": "TH",
    "TJ": "TJ", "Tajikistan": "TJ", "Tayikistan": "TJ", "Тоҷикистон": "TJ", "Таджикистан": "TJ",
    "TK": "TK", "Tokelau": "TK",
    "TL": "TL", "Timor-Leste": "TL", "East Timor": "TL", "Timor Oriental": "TL", "Timór Lorosa'e": "TL",
    "TM": "TM", "Turkmenistan": "TM", "Turkmenia": "TM", "Түркменистан": "TM",
    "TN": "TN", "Tunisia": "TN", "Tunez": "TN", "تونس‎": "TN",
    "TO": "TO", "Tonga": "TO",
    "TR": "TR", "Turkey": "TR", "Turquia": "TR", "Türkiye": "TR",
    "TT": "TT", "Trinidad and Tobago": "TT", "Trinidad y Tobago": "TT",
    "TV": "TV", "Tuvalu": "TV",
    "TW": "TW", "Taiwan": "TW",
    "TZ": "TZ", "Tanzania": "TZ",
    "UA": "UA", "Ukraine": "UA", "Ucrania": "UA", "Україна": "UA", "Ukrayina": "UA",
    "UG": "UG", "Uganda": "UG",
    "US": "US", "United States of America": "US", "United States": "US", "Estados Unidos": "US", "USA": "US",
    "UY": "UY", "Uruguay": "UY", "Uruguai": "UY",
    "UZ": "UZ", "Uzbekistan": "UZ",
    "VA": "VA", "Vatican City": "VA", "Status Civitatis Vaticanae": "VA", "Città del Vaticano": "VA", "Ciudad del Vaticano": "VA",
    "VC": "VC", "Saint Vincent and the Grenadines": "VC", "Saint Vincent": "VC", "San Vicente y las Granadinas": "VC",
    "VE": "VE", "Venezuela": "VE",
    "VG": "VG", "British Virgin Islands": "VG", "BVI": "VG", "Islas Vírgenes Británicas": "VG",
    "VI": "VI", "American Virgin Islands": "VI", "United States Virgin Islands": "VI", "USVI": "VI", "Islas Vírgenes Americanas": "VI",
    "VN": "VN", "Viet Nam": "VN", "Vietnam": "VN",
    "VU": "VU", "Vanuatu": "VU",
    "WS": "WS", "Samoa": "WS",
    "XK": "XK", "Kosovo": "XK", "Kosova": "XK", "Kosove": "XK", "Косово": "XK",
    "YE": "YE", "Yemen": "YE", "اليَمَن": "YE",
    "ZA": "ZA", "South Africa": "ZA", "Sudafrica": "ZA",
    "ZM": "ZM", "Zambia": "ZM",
    "ZW": "ZW", "Zimbabwe": "ZW", "Zimbabue": "ZW",
};


module.exports.countries_es = {
    "AD": ":flag_ad: Andorra", "AE": ":flag_ae: Emiratos Árabes Unidos", "AG": ":flag_ag: Antigua y Barbuda",
    "AL": ":flag_al: Albania", "AM": ":flag_am: Armenia", "AR": ":flag_ar: Argentina", "AT": ":flag_at: Austria",
    "AU": ":flag_au: Australia", "AW": ":flag_aw: Aruba", "AX": ":flag_ax: Islas Åland", "AZ": ":flag_az: Azerbaiyán",
    "BA": ":flag_ba: Bosnia y Herzegovina", "BB": ":flag_bb: Barbados", "BD": ":flag_bd: Bangladés", "BE": ":flag_be: Bélgica",
    "BG": ":flag_bg: Bulgaria", "BH": ":flag_bh: Baréin", "BM": ":flag_bm: Bermudas", "BN": ":flag_bn: Brunéi", "BO": ":flag_bo: Bolivia",
    "BR": ":flag_br: Brasil", "BS": ":flag_bs: Bahamas", "BY": ":flag_by: Bielorrusia", "BZ": ":flag_bz: Belice", "CA": ":flag_ca: Canadá",
    "CF": ":flag_cf: República Centroafricana", "CH": ":flag_ch: Suiza", "CI": ":flag_ci: Costa de Marfil", "CL": ":flag_cl: Chile",
    "CN": ":flag_cn: China", "CO": ":flag_co: Colombia", "CR": ":flag_cr: Costa Rica", "CY": ":flag_cy: Chipre", "CZ": ":flag_cz: República Checa",
    "DE": ":flag_de: Alemania", "DK": ":flag_dk: Dinamarca", "DO": ":flag_do: República Dominicana", "DZ": ":flag_dz: Argelia", "EC": ":flag_ec: Ecuador",
    "EE": ":flag_ee: Estonia", "EG": ":flag_eg: Egipto", "ER": ":flag_er: Eritrea", "ES": ":flag_es: España", "EU": ":flag_eu: Unión Europea",
    "FI": ":flag_fi: Finlandia", "FO": ":flag_fo: Islas Feroe", "FR": ":flag_fr: Francia", "GE": ":flag_ge: Georgia", "GF": ":flag_gf: Guayana Francesa",
    "GG": ":flag_gg: Guernsey", "GI": ":flag_gi: Gibraltar", "GL": ":flag_gl: Groenlandia", "GP": ":flag_gp: Guadalupe", "GR": ":flag_gr: Grecia",
    "GT": ":flag_gt: Guatemala", "GU": ":flag_gu: Guam", "GY": ":flag_gy: Guyana", "HK": ":flag_hk: Hong Kong", "HN": ":flag_hn: Honduras",
    "HR": ":flag_hr: Croacia", "HU": ":flag_hu: Hungría", "ID": ":flag_id: Indonesia", "IE": ":flag_ie: Irlanda", "IL": ":flag_il: Israel",
    "IM": ":flag_im: Isla de Man", "IN": ":flag_in: India", "IQ": ":flag_iq: Irak", "IR": ":flag_ir: Irán", "IS": ":flag_is: Islandia",
    "IT": ":flag_it: Italia", "JE": ":flag_je: Jersey", "JM": ":flag_jm: Jamaica", "JO": ":flag_jo: Jordania", "JP": ":flag_jp: Japón",
    "KE": ":flag_ke: Kenia", "KG": ":flag_kg: Kirguistán", "KH": ":flag_kh: Camboya", "KR": ":flag_kr: Corea del Sur", "KW": ":flag_kw: Kuwait",
    "KZ": ":flag_kz: Kazajistán", "LA": ":flag_la: Laos", "LB": ":flag_lb: Líbano", "LC": ":flag_lc: Santa Lucía", "LI": ":flag_li: Liechtenstein",
    "LK": ":flag_lk: Sri Lanka", "LR": ":flag_lr: Liberia", "LT": ":flag_lt: Lituania", "LU": ":flag_lu: Luxemburgo", "LV": ":flag_lv: Letonia",
    "LY": ":flag_ly: Libia", "MA": ":flag_ma: Marruecos", "MD": ":flag_md: Moldavia", "ME": ":flag_me: Montenegro", "MG": ":flag_mg: Madagascar",
    "MK": ":flag_mk: República de Macedonia", "MM": ":flag_mm: Birmania", "MN": ":flag_mn: Mongolia", "MO": ":flag_mo: Macao", "MP": ":flag_mp: Islas Marianas del Norte",
    "MQ": ":flag_mq: Martinica", "MT": ":flag_mt: Malta", "MU": ":flag_mu: Mauricio", "MV": ":flag_mv: Maldivas", "MX": ":flag_mx: México", "MY": ":flag_my: Malasia",
    "NC": ":flag_nc: Nueva Caledonia", "NI": ":flag_ni: Nicaragua", "NL": ":flag_nl: Países Bajos", "NO": ":flag_no: Noruega", "NP": ":flag_np: Nepal",
    "NZ": ":flag_nz: Nueva Zelanda", "OM": ":flag_om: Omán", "PA": ":flag_pa: Panamá", "PE": ":flag_pe: Perú", "PF": ":flag_pf: Polinesia Francesa",
    "PH": ":flag_ph: Filipinas", "PK": ":flag_pk: Pakistán", "PL": ":flag_pl: Polonia", "PM": ":flag_pm: San Pedro y Miquelón", "PR": ":flag_pr: Puerto Rico",
    "PS": ":flag_ps: Palestina", "PT": ":flag_pt: Portugal", "PY": ":flag_py: Paraguay", "QA": ":flag_qa: Catar", "RE": ":flag_re: Reunión",
    "RO": ":flag_ro: Rumanía", "RS": ":flag_rs: Serbia", "RU": ":flag_ru: Rusia", "SA": ":flag_sa: Arabia Saudita", "SD": ":flag_sd: Sudán",
    "SE": ":flag_se: Suecia", "SG": ":flag_sg: Singapur", "SI": ":flag_si: Eslovenia", "SK": ":flag_sk: Eslovaquia", "SN": ":flag_sn: Senegal",
    "SR": ":flag_sr: Surinam", "SV": ":flag_sv: El Salvador", "SY": ":flag_sy: Siria", "TH": ":flag_th: Tailandia", "TJ": ":flag_tj: Tayikistán",
    "TN": ":flag_tn: Túnez", "TR": ":flag_tr: Turquía", "TT": ":flag_tt: Trinidad y Tobago", "TW": ":flag_tw: Taiwán", "UA": ":flag_ua: Ucrania",
    "UK": ":flag_gb: Reino Unido", "US": ":flag_us: Estados Unidos", "UY": ":flag_uy: Uruguay", "UZ": ":flag_uz: Uzbekistán", "VE": ":flag_ve: Venezuela",
    "VI": ":flag_vi: Islas Vírgenes de los Estados Unidos", "VN": ":flag_vn: Vietnam", "ZA": ":flag_za: Sudáfrica"
};
